package rules;
import com.example.springboot.springboot.drools.entity.Person;
dialect  "mvel"

rule "age1"
    when
        $person : Person(age > 0 , age <= 10)
    then
        System.out.println("这个人的年龄属于1-10岁");
end

rule "age2"
    when
        $person : Person(age > 10 , age <= 20)
    then
        System.out.println("这个人的年龄属于11-20岁");
end

rule "person"
    when
        eval(true)
    then
        System.out.print("====================");
    end
